import React, { useState, useEffect } from 'react';
import { Lightbulb, Sparkles, Target, ArrowRight, CheckCircle2, AlertTriangle, BookOpen, RefreshCw } from 'lucide-react';
import { StudentProfile, WeaknessItem, AISuggestion } from '../types';
import { fetchSuggestions } from '../services/api';

interface SuggestionsViewProps {
  profile: StudentProfile | null;
  weaknesses: WeaknessItem[];
  onNavigate: (tab: string) => void;
}

export const SuggestionsView: React.FC<SuggestionsViewProps> = ({ profile, weaknesses, onNavigate }) => {
  const targetCompany = profile?.target_company || 'Amazon';
  const [suggestions, setSuggestions] = useState<AISuggestion[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const loadSuggestions = async () => {
    setIsLoading(true);
    try {
      const data = await fetchSuggestions();
      setSuggestions(data || []);
    } catch (err) {
      console.error('Error fetching suggestions:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadSuggestions();
  }, [profile]);

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="glass-card p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold subtle-badge-indigo">
              AI Recommendations Engine
            </span>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold subtle-badge-emerald">
              Memory & Evidence Guided
            </span>
          </div>
          <h2 className="text-xl font-black text-white tracking-tight">Adaptive Suggestions & Recommendations</h2>
          <p className="text-xs text-slate-300 font-medium mt-0.5">
            Data-driven recommendations generated by analyzing your recent assessment outcomes, mistake memory logs, and {targetCompany} assessment weighting.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-indigo-300 bg-indigo-950/60 px-3 py-1.5 rounded-lg border border-indigo-500/30">
            🎯 Company Context: {targetCompany}
          </span>
        </div>
      </div>

      {/* Suggestions List */}
      <div className="space-y-4">
        {suggestions.map((sug) => {
          const isHigh = sug.priority === 'High';
          return (
            <div key={sug.id} className="glass-card p-6 border-l-4 border-l-indigo-500 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-white/10 pb-3">
                <div className="flex items-center gap-2">
                  <Lightbulb className="w-5 h-5 text-indigo-400" />
                  <h3 className="text-base font-bold text-white">{sug.title}</h3>
                </div>

                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-0.5 rounded text-xs font-bold subtle-badge-indigo">
                    {sug.category}
                  </span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold subtle-badge-amber">
                    {sug.priority} Priority
                  </span>
                </div>
              </div>

              <div className="space-y-2 text-xs text-slate-300">
                <p className="font-semibold text-slate-200 leading-relaxed">{sug.description}</p>
                <div className="p-3 rounded-lg bg-slate-950/70 border border-white/10 text-[11px] text-slate-300 font-mono">
                  <span className="font-bold text-indigo-400">Agent Memory Evidence: </span>
                  {sug.evidence}
                </div>
              </div>

              {/* Recommended Action Checklist */}
              <div className="space-y-1.5 pt-1">
                <span className="text-xs font-bold text-slate-200">Recommended Action Plan:</span>
                <div className="space-y-1">
                  {sug.recommended_actions.map((act, idx) => (
                    <div key={idx} className="flex items-center gap-2 text-xs text-slate-300">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
                      <span>{act}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Action Button */}
              <div className="pt-2 flex justify-end">
                <button
                  onClick={() => onNavigate(sug.action_target)}
                  className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-600/30 transition-all flex items-center gap-1.5 active:scale-95"
                >
                  <span>{sug.action_label}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
